# Generated by Django 4.2.11 on 2025-03-02 23:41

import bookings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default=bookings.models.get_default_movie, on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
